# ── fix_regulatory_realtime.R ─────────────────────────────────────────────────
# Run from:
#   cd C:\Users\drhas\Documents\diabetes-trial-edi-equity\edi-recruitment-bias-monitoring\python
#   Rscript fix_regulatory_realtime.R
#
# What this does: replaces the hardcoded regulatory EDI server block in app.R
# with fully reactive code that reads regulatory_edi_scored.csv at runtime.
# No hardcoded percentages, counts, or trial numbers anywhere.
# ─────────────────────────────────────────────────────────────────────────────

app_path <- "app.R"
lines    <- readLines(app_path, warn = FALSE)

REG_CSV <- paste0(
  "C:/Users/drhas/Documents/diabetes-trial-edi-equity/",
  "edi-recruitment-bias-monitoring/python/regulatory_edi_scored.csv"
)

# ── Find the start and end of the regulatory server block ────────────────────
start_line <- grep("# -- Regulatory EDI", lines)
if (length(start_line) == 0) stop("Could not find '# -- Regulatory EDI' marker")
start_line <- start_line[1]

# Find the closing empty line after the last re_ output block
# Look for the next server section or end server marker after start_line
end_candidates <- grep("^\\s*$|# --|} # end server|\\} # end server", lines)
end_line <- min(end_candidates[end_candidates > start_line + 5])

cat(sprintf("Replacing lines %d–%d with reactive server code...\n",
            start_line, end_line))

# ── New fully reactive server block ──────────────────────────────────────────
new_block <- c(
  "",
  "  # -- Regulatory EDI --------------------------------------------------------",
  paste0('  REG_CSV <- "', REG_CSV, '"'),
  "",
  "  reg_r <- reactive({",
  "    if (!file.exists(REG_CSV)) {",
  "      showNotification('regulatory_edi_scored.csv not found — run Cell 13 first.',",
  "                       type = 'error', duration = 10)",
  "      return(NULL)",
  "    }",
  "    read.csv(REG_CSV, stringsAsFactors = FALSE)",
  "  })",
  "",
  "  output$re1 <- renderValueBox({",
  "    df <- reg_r(); req(df)",
  "    vb(paste0(round(mean(df$ema_compliance_pct, na.rm=TRUE), 1), '%'),",
  "       paste0('Mean EMA Compliance  (n=', nrow(df), ')'),",
  "       'file-contract', 'yellow')",
  "  })",
  "",
  "  output$re2 <- renderValueBox({",
  "    df <- reg_r(); req(df)",
  "    vb(paste0(round(mean(df$fda_compliance_pct, na.rm=TRUE), 1), '%'),",
  "       'Mean FDA Compliance', 'file-medical', 'red')",
  "  })",
  "",
  "  output$re3 <- renderValueBox({",
  "    df <- reg_r(); req(df)",
  "    n_c <- sum(df$reg_gap_grade == 'Compliant', na.rm=TRUE)",
  "    vb(paste0(round(n_c / nrow(df) * 100, 1), '%'),",
  "       'Trials Compliant (Both)', 'check-double', 'green')",
  "  })",
  "",
  "  output$re4 <- renderValueBox({",
  "    df <- reg_r(); req(df)",
  "    n_g <- sum(df$reg_gap_grade == 'Critical Gap', na.rm=TRUE)",
  "    vb(paste0(round(n_g / nrow(df) * 100, 1), '%'),",
  "       'Critical Gap (Both)', 'exclamation-circle', 'red')",
  "  })",
  "",
  "  output$re_ema_crit <- renderPlotly({",
  "    df <- reg_r(); req(df)",
  "    ema_cols   <- c('ema_age_inclusive','ema_sex_inclusive','ema_comorbidity_open',",
  "                    'ema_subgroup_planned','ema_geriatric_mention','ema_diversity_rationale')",
  "    ema_labels <- c('Age inclusive','Sex inclusive','Comorbidity open',",
  "                    'Subgroup planned','Geriatric mention','Diversity rationale')",
  "    ema_cols   <- ema_cols[ema_cols %in% names(df)]",
  "    ema_labels <- ema_labels[seq_along(ema_cols)]",
  "    pct <- round(colMeans(df[, ema_cols, drop=FALSE], na.rm=TRUE) * 100, 1)",
  "    d   <- data.frame(crit=ema_labels, pct=pct)[order(pct), ]",
  "    bc  <- ifelse(d$pct >= 60, GREEN, ifelse(d$pct >= 30, AMBER, RED))",
  "    plot_ly(d, y=~reorder(crit,pct), x=~pct, type='bar', orientation='h',",
  "            marker=list(color=bc),",
  "            text=~paste0(pct,'%'), textposition='outside') %>%",
  "      layout(xaxis=list(title='% Trials Meeting Criterion', range=c(0,115)),",
  "             yaxis=list(title=''),",
  "             paper_bgcolor='white', plot_bgcolor='white', showlegend=FALSE)",
  "  })",
  "",
  "  output$re_fda_crit <- renderPlotly({",
  "    df <- reg_r(); req(df)",
  "    fda_cols   <- c('fda_sex_goal','fda_race_goal','fda_age_plan',",
  "                    'fda_barrier_address','fda_underrep_group')",
  "    fda_labels <- c('Sex enrolment goal','Race/ethnicity goal','Age plan (geriatric)',",
  "                    'Barrier addressed','Underrep group stated')",
  "    fda_cols   <- fda_cols[fda_cols %in% names(df)]",
  "    fda_labels <- fda_labels[seq_along(fda_cols)]",
  "    pct <- round(colMeans(df[, fda_cols, drop=FALSE], na.rm=TRUE) * 100, 1)",
  "    d   <- data.frame(crit=fda_labels, pct=pct)[order(pct), ]",
  "    bc  <- ifelse(d$pct >= 60, GREEN, ifelse(d$pct >= 30, AMBER, RED))",
  "    plot_ly(d, y=~reorder(crit,pct), x=~pct, type='bar', orientation='h',",
  "            marker=list(color=bc),",
  "            text=~paste0(pct,'%'), textposition='outside') %>%",
  "      layout(xaxis=list(title='% Trials Meeting Criterion', range=c(0,115)),",
  "             yaxis=list(title=''),",
  "             paper_bgcolor='white', plot_bgcolor='white', showlegend=FALSE)",
  "  })",
  "",
  "  output$re_scatter <- renderPlotly({",
  "    df <- reg_r(); req(df)",
  "    col_map <- c('Critical Gap'=RED,'Substantial Gap'=AMBER,",
  "                 'Moderate Gap'=BLUE,'Compliant'=GREEN)",
  "    bc <- unname(col_map[as.character(df$reg_gap_grade)])",
  "    bc[is.na(bc)] <- '#CCCCCC'",
  "    plot_ly(df, x=~ema_compliance_pct, y=~fda_compliance_pct,",
  "            type='scatter', mode='markers',",
  "            marker=list(color=bc, size=5, opacity=0.45),",
  "            showlegend=FALSE) %>%",
  "      add_segments(x=50, xend=50, y=-5, yend=105,",
  "                   line=list(color='#CCCCCC', dash='dash', width=1),",
  "                   showlegend=FALSE) %>%",
  "      add_segments(x=-5, xend=105, y=50, yend=50,",
  "                   line=list(color='#CCCCCC', dash='dash', width=1),",
  "                   showlegend=FALSE) %>%",
  "      layout(xaxis=list(title='EMA Compliance (%)', range=c(-5,105)),",
  "             yaxis=list(title='FDA Compliance (%)', range=c(-5,105)),",
  "             paper_bgcolor='white', plot_bgcolor='white')",
  "  })",
  "",
  "  output$re_trend <- renderPlotly({",
  "    df  <- reg_r(); req(df)",
  "    col <- if (input$re_agency == 'ema') 'ema_compliance_pct' else 'fda_compliance_pct'",
  "    gyr <- if (input$re_agency == 'ema') 2023 else 2022",
  "    gc  <- if (input$re_agency == 'ema') NAVY else BLUE",
  "    df$start_year <- as.numeric(df$start_year)",
  "    tr <- df %>%",
  "      dplyr::group_by(start_year) %>%",
  "      dplyr::summarise(mean_val=mean(.data[[col]], na.rm=TRUE),",
  "                       n=dplyr::n(), .groups='drop') %>%",
  "      dplyr::filter(n >= 3, start_year >= 2000, !is.na(start_year))",
  "    ymax <- max(tr$mean_val, na.rm=TRUE) * 1.1",
  "    plot_ly(tr, x=~start_year, y=~mean_val,",
  "            type='scatter', mode='lines+markers',",
  "            line=list(color=gc, width=2.5),",
  "            marker=list(color=gc, size=6),",
  "            hovertemplate='Year: %{x}<br>Mean: %{y:.1f}%<br>n=%{customdata}',",
  "            customdata=~n) %>%",
  "      add_segments(x=gyr, xend=gyr, y=0, yend=ymax,",
  "                   line=list(color=RED, dash='dash', width=2),",
  "                   showlegend=FALSE) %>%",
  "      layout(xaxis=list(title='Trial Start Year (\\u2260 protocol design date)'),",
  "             yaxis=list(title='Mean Compliance (%)'),",
  "             annotations=list(list(x=gyr, y=ymax,",
  "               text=paste0('Guidance\\n(', gyr, ')'),",
  "               showarrow=FALSE, font=list(color=RED, size=9))),",
  "             paper_bgcolor='white', plot_bgcolor='white', showlegend=FALSE)",
  "  })",
  "",
  "  output$re_country <- renderPlotly({",
  "    df <- reg_r(); req(df)",
  "    eu_l <- c('Ireland','United Kingdom','France','Netherlands','Switzerland',",
  "              'Germany','Italy','Spain','Belgium','Sweden','Norway','Denmark',",
  "              'Finland','Austria','Portugal','Poland','Czech Republic',",
  "              'Hungary','Romania','Croatia','Greece')",
  "    if (!('countries' %in% names(df))) return(plotly_empty())",
  "    rows <- do.call(rbind, lapply(seq_len(nrow(df)), function(i) {",
  "      ctrs <- trimws(unlist(strsplit(as.character(df$countries[i]), '\\\\|')))",
  "      ctrs <- ctrs[ctrs %in% eu_l]",
  "      if (!length(ctrs)) return(NULL)",
  "      data.frame(country=ctrs,",
  "                 ema=df$ema_compliance_pct[i],",
  "                 fda=df$fda_compliance_pct[i],",
  "                 stringsAsFactors=FALSE)",
  "    }))",
  "    if (is.null(rows) || nrow(rows) == 0) return(plotly_empty())",
  "    agg <- aggregate(cbind(ema,fda) ~ country, data=rows, FUN=mean)",
  "    agg$n <- as.integer(table(rows$country)[agg$country])",
  "    agg <- agg[agg$n >= input$re_minn, ]",
  "    if (nrow(agg) == 0) return(plotly_empty())",
  "    agg <- agg[order(agg$ema), ]",
  "    plot_ly() %>%",
  "      add_bars(y=agg$country, x=round(agg$ema,1),",
  "               orientation='h', name='EMA %',",
  "               marker=list(color=NAVY)) %>%",
  "      add_bars(y=agg$country, x=round(agg$fda,1),",
  "               orientation='h', name='FDA %',",
  "               marker=list(color=BLUE, opacity=0.8)) %>%",
  "      layout(barmode='overlay',",
  "             xaxis=list(title='Compliance Score (%)'),",
  "             yaxis=list(title='', categoryorder='array',",
  "                        categoryarray=agg$country),",
  "             legend=list(orientation='h', y=-0.15),",
  "             paper_bgcolor='white', plot_bgcolor='white')",
  "  })",
  "",
  "  output$re_gap_pie <- renderPlotly({",
  "    df  <- reg_r(); req(df)",
  "    ord <- c('Critical Gap','Substantial Gap','Moderate Gap','Compliant')",
  "    tbl <- table(factor(as.character(df$reg_gap_grade), levels=ord))",
  "    plot_ly(labels=names(tbl), values=as.numeric(tbl), type='pie',",
  "            marker=list(colors=c(RED,AMBER,BLUE,GREEN),",
  "                        line=list(color='white', width=2)),",
  "            textinfo='label+percent',",
  "            hovertemplate='%{label}: %{value} trials (%{percent})<extra></extra>') %>%",
  "      layout(showlegend=TRUE,",
  "             legend=list(orientation='h', y=-0.15),",
  "             paper_bgcolor='white')",
  "  })",
  ""
)

# ── Splice in new block ───────────────────────────────────────────────────────
lines_new <- c(lines[1:(start_line - 1)], new_block, lines[(end_line):length(lines)])
writeLines(lines_new, app_path)
cat(sprintf("✓ Done. app.R updated: %d lines total.\n", length(lines_new)))
cat("  All regulatory EDI metrics now computed live from CSV.\n")
cat("  Run: Rscript -e \"shiny::runApp('app.R', port=8787)\"\n")
